CREATE TABLE IF NOT EXISTS Usuario (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username text NOT NULL CHECK (username <> ''),    
    email text NOT NULL UNIQUE,  
    password text NOT NULL,    
    imagen text,
    telefono text,
    empresa text,
    instagram_link text,
    facebook_link text,
    twitter_link text,
    wallet_address text,
    rol text DEFAULT 'user'
    
);

-- Cambiar el rol a admin
UPDATE usuario SET rol='admin' WHERE email='felix@gmail.com';

-- Cambiar validado a TRUE
UPDATE usuario SET validado=TRUE WHERE email='alberto@gmail.com';

UPDATE usuario SET validado=TRUE WHERE id=1;


-- Agregar campo 'validado'
ALTER TABLE usuario ADD COLUMN "validado" BOOLEAN DEFAULT FALSE;

-- Agregar campos para programa de referidos
ALTER TABLE usuario ADD COLUMN "referido" text;
ALTER TABLE usuario ADD COLUMN "referido_por" text;

-- Agregar constraint not null a usuario luego de ingresar los códigos por base de datos
ALTER TABLE usuario ALTER COLUMN referido SET NOT NULL;




