CREATE TABLE IF NOT EXISTS Usuario (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username text NOT NULL CHECK (username <> ''),    
    email text NOT NULL UNIQUE,  
    password text NOT NULL,    
    imagen text,
    telefono text,
    empresa text,
    instagram_link text,
    facebook_link text,
    twitter_link text,
    wallet_address text,
    rol text DEFAULT 'user'
    
);

-- Agregar campo 'validado'
ALTER TABLE usuario ADD COLUMN "validado" BOOLEAN DEFAULT FALSE;

-- Agregar campos para programa de referidos
ALTER TABLE usuario ADD COLUMN "referido" text;
ALTER TABLE usuario ADD COLUMN "referido_por" text;


-- Agregar constraint not null a usuario luego de ingresar los códigos por base de datos
ALTER TABLE usuario ALTER COLUMN referido SET NOT NULL;


-- Agregar campos creado en y modificado en
ALTER TABLE usuario ADD COLUMN creado_en TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE usuario ADD COLUMN modificado_en TIMESTAMPTZ DEFAULT NOW();

-- Agregar constraint not null a campos creado_en y modificado_en
ALTER TABLE usuario ALTER COLUMN creado_en SET NOT NULL;
ALTER TABLE usuario ALTER COLUMN modificado_en SET NOT NULL;

-- Agregar campo fecha_pago para registrar la fecha en la que se realizó el pago
ALTER TABLE usuario ADD COLUMN fecha_pago TIMESTAMPTZ DEFAULT to_timestamp(0);
ALTER TABLE usuario ALTER COLUMN fecha_pago SET NOT NULL;

