CREATE TABLE IF NOT EXISTS Usuario (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username text NOT NULL CHECK (username <> ''),    
    email text NOT NULL UNIQUE,  
    password text NOT NULL,    
    imagen text,
    telefono text,
    empresa text,
    instagram_link text,
    facebook_link text,
    twitter_link text,
    wallet_address text,
    rol text DEFAULT 'user'
    
);

-- Cambiar el rol a admin
UPDATE usuario SET rol='admin' WHERE email='felix@gmail.com';

-- Cambiar validado a TRUE
UPDATE usuario SET validado=TRUE WHERE email='alberto@gmail.com';

UPDATE usuario SET validado=TRUE WHERE id=1;


-- Agregar campo 'validado'
ALTER TABLE usuario ADD COLUMN "validado" BOOLEAN DEFAULT FALSE;

-- Agregar campos para programa de referidos
ALTER TABLE usuario ADD COLUMN "referido" text;
ALTER TABLE usuario ADD COLUMN "referido_por" text;


-- Agregar código de referido a los usuarios que están en la base de datos
UPDATE usuario SET referido='ZD0Kq5gShTN8j012BQQFF' WHERE id=1;
UPDATE usuario SET referido='1fan1a7WMBGytdTvwPKfr' WHERE id=2;
UPDATE usuario SET referido='bO8YtRxVCjBdT1J4d-cOb' WHERE id=3;
UPDATE usuario SET referido='TzL2TLQzuwGnPvpXWQgQZ' WHERE id=4;
UPDATE usuario SET referido='OF7doqQ87om0KavD9dsHz' WHERE id=5;
UPDATE usuario SET referido='NLxnvyjEN5sJjvGQzMtQd' WHERE id=6;
UPDATE usuario SET referido='cxxb08DvhmPfT5MLXs0Er' WHERE id=7;
UPDATE usuario SET referido='8w3GiG3Ivq7eK2yqQV1tq' WHERE id=8;
UPDATE usuario SET referido='2mKdnH7yAx1xomD4rfqen' WHERE id=9;
UPDATE usuario SET referido='F5nPCtHGNsgGsCa2mO4Es' WHERE id=10;
UPDATE usuario SET referido='6kScgFDzRiaNdSh6ToLTG' WHERE id=11;
UPDATE usuario SET referido='lhETAUvAF9pkmlQh867xb' WHERE id=12;
UPDATE usuario SET referido='IOjcpYfDY6iNNAoytfITC' WHERE id=13;
UPDATE usuario SET referido='kKd07rM0PvO5UXw994vJE' WHERE id=14;
UPDATE usuario SET referido='J6HdK7yd_7PingjA3jzaK' WHERE id=15;
UPDATE usuario SET referido='2oK0tVVzzXiLzm33PU7sG' WHERE id=16;
UPDATE usuario SET referido='z_cJnZqnlYEZwAOJ1M9d5' WHERE id=17;
UPDATE usuario SET referido='6QGn4HcImdWCpIYmRhwue' WHERE id=18;


-- Agregar constraint not null a usuario luego de ingresar los códigos por base de datos
ALTER TABLE usuario ALTER COLUMN referido SET NOT NULL;






